"""Initial migration: create users, sessions, session_state tables

Revision ID: 950bd54c7a60
Revises: 
Create Date: 2025-12-12 15:41:40.928490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql, sqlite

# AI Generated Code by Deloitte + Cursor (BEGIN)

# revision identifiers, used by Alembic.
revision: str = '950bd54c7a60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Detect database type
    bind = op.get_bind()
    is_postgres = bind.dialect.name == 'postgresql'
    is_sqlite = bind.dialect.name == 'sqlite'
    
    # ### commands auto generated by Alembic - please adjust! ###
    # Use JSONB for PostgreSQL, JSON for SQLite
    state_column_type = postgresql.JSONB() if is_postgres else sa.JSON()
    
    op.create_table('session_state',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('state', state_column_type, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_cost_usd', sa.Float(), nullable=True),
    sa.Column('last_total_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_is_deleted'), 'sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###
    
    # SQLite-specific optimizations
    if is_sqlite:
        op.execute(sa.text("PRAGMA journal_mode=WAL"))
        op.execute(sa.text("PRAGMA busy_timeout=60000"))
        op.execute(sa.text("PRAGMA synchronous=NORMAL"))
    
    # PostgreSQL-specific: GIN index for JSONB queries
    if is_postgres:
        op.execute(sa.text(
            "CREATE INDEX IF NOT EXISTS ix_session_state_state_gin "
            "ON session_state USING gin (state)"
        ))
# AI Generated Code by Deloitte + Cursor (END)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_deleted'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('session_state')
    # ### end Alembic commands ###
